# Generated by Django 4.2.6 on 2024-04-03 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
                ('poste', models.CharField(max_length=255, unique=True)),
                ('domicile', models.CharField(max_length=255)),
                ('tell', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes_user', to=settings.AUTH_USER_MODEL)),
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe_user_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_location.employe')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
