# Generated by Django 4.2.6 on 2024-03-23 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('s_name', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='image/')),
                ('adresse', models.CharField(max_length=30)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=45)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('adresse', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('indisponible', 'Indisponible'), ('disponible', 'Disponible'), ('loue', 'Loué'), ('vente', 'En vente')], max_length=20)),
                ('type_propriete', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain'), ('autre', 'Autre')], max_length=20)),
                ('nombre_chambres', models.PositiveIntegerField()),
                ('nombre_salles_bains', models.PositiveIntegerField()),
                ('surface_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat_bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propriete', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.propriete')),
            ],
        ),
    ]
