# Generated by Django 4.2.6 on 2024-04-04 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('tell', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('pas_actif', 'Pas_actif')], max_length=20)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propriete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.propriete')),
            ],
        ),
        migrations.CreateModel(
            name='Signaler_panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(max_length=500)),
                ('locateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signaler_une_panne', to='locateur.locateur')),
            ],
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Locateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locateur.locateur')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
